### ISSUE TITLE
Unknown blocks

### ISSUE THREAD

**Issue by ga6rielsilva** [Wertik/BlockRegen#31]
I'm constantly getting this error on my console, because of a modded block, how can I make it just ignore that block(s)?

```
[00:15:06] [Server thread/ERROR] [Minecraft]: Could not pass event PlayerInteractEvent to BlockRegen v3.10.1
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:1.12.2-3e8d3acf]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:1.12.2-3e8d3acf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.12.2-3e8d3acf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) ~[SimplePluginManager.class:1.12.2-3e8d3acf]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:263) ~[CraftEventFactory.class:1.12.2-3e8d3acf]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:230) ~[CraftEventFactory.class:1.12.2-3e8d3acf]
        at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:144) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1077) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
        at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.IllegalArgumentException: Unsupported material from item: IC2_SAPLING (0)
        at nl.aurorion.blockregen.xseries.XMaterial.matchXMaterial(XMaterial.java:1774) ~[?:?]
        at nl.aurorion.blockregen.listeners.PlayerListener.onInteract(PlayerListener.java:45) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor644.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:1.12.2-3e8d3acf]
        ... 18 more
```

**Comment by Wertik** [comment]
Unfortunately mods aren't supported. Maybe in the future.
