### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by noiverre** [Wertik/BlockRegen#36]
```
[05:35:13] [ForkJoinPool.commonPool-worker-1/INFO]: [BlockRegen] SEVERE: Could not load processes: java.lang.NullPointerException: Cannot invoke "nl.aurorion.blockregen.system.regeneration.struct.RegenerationProcess.convertLocation()" because "process" is null
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "nl.aurorion.blockregen.system.regeneration.struct.RegenerationProcess.convertLocation()" because "process" is null
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "nl.aurorion.blockregen.system.regeneration.struct.RegenerationProcess.convertLocation()" because "process" is null
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at BlockRegen-3.10.7.jar//nl.aurorion.blockregen.system.regeneration.RegenerationManager.lambda$load$4(RegenerationManager.java:239)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[05:35:13] [ForkJoinPool.commonPool-worker-1/WARN]: 	... 6 more
```

Version: 3.10.7

**Comment by Wertik** [comment]
Hey, sorry for the extremely late reply. Your issue was most likely fixed in 3.11.4. Download here on github from the releases page.
