### ISSUE TITLE
Regeneration fails with onDisable on server restart

### ISSUE THREAD

**Issue by alpoi-old** [Wertik/BlockRegen#39]
**Server version**: `purpur-1.21.1.jar:1.21.1-2297-ef12ede`
**Plugin version**: `BlockRegen-3.10.8.jar`
**Expected Behaviour**: When restarting the server, all registered blocks are regenerated
**Observed Behaviour**: When restarting the server, an `IllegalPluginAccessException` is thrown and blocks are not regenerated. This sometimes leads to the blocks _never_ being regenerated.

**Stack Trace**
```
[22:00:54 INFO]: [BlockRegen] Disabling BlockRegen v3.10.8
[22:00:54 ERROR]: Error occurred while disabling BlockRegen v3.10.8
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.validate(CraftScheduler.java:539) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:219) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:210) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:174) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:143) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at BlockRegen-3.10.8.jar/nl.aurorion.blockregen.system.regeneration.struct.RegenerationProcess.regenerateBlock(RegenerationProcess.java:182) ~[BlockRegen-3.10.8.jar:?]
        at BlockRegen-3.10.8.jar/nl.aurorion.blockregen.system.regeneration.RegenerationManager.purgeExpired(RegenerationManager.java:197) ~[BlockRegen-3.10.8.jar:?]
        at BlockRegen-3.10.8.jar/nl.aurorion.blockregen.system.regeneration.RegenerationManager.save(RegenerationManager.java:211) ~[BlockRegen-3.10.8.jar:?]
        at BlockRegen-3.10.8.jar/nl.aurorion.blockregen.BlockRegen.onDisable(BlockRegen.java:257) ~[BlockRegen-3.10.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:623) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1059) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:887) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1013) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:41) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:32) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1791) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2297-ef12ede]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

It appears that the issue arises from the plugin trying to register the regeneration task after the plugin has been disabled:
https://github.com/Wertik/BlockRegen/blob/master/blockregen-plugin/src/main/java/nl/aurorion/blockregen/system/regeneration/struct/RegenerationProcess.java#L182

**Comment by Wertik** [comment]
Should be resolved in 3.11.2
